# Generated by Django 4.2.1 on 2023-05-14 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="name",
        ),
    ]
