# Generated by Django 4.2.1 on 2023-05-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
