# Generated by Django 4.2.1 on 2023-05-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_file_file_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(to="api.technology"),
        ),
    ]
